#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BOOP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Klasifikace")]
	public partial class KlasifikaceDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFakulty(Fakulty instance);
    partial void UpdateFakulty(Fakulty instance);
    partial void DeleteFakulty(Fakulty instance);
    partial void InsertStudenti(Studenti instance);
    partial void UpdateStudenti(Studenti instance);
    partial void DeleteStudenti(Studenti instance);
    partial void InsertHodnoceni(Hodnoceni instance);
    partial void UpdateHodnoceni(Hodnoceni instance);
    partial void DeleteHodnoceni(Hodnoceni instance);
    partial void InsertZnamky(Znamky instance);
    partial void UpdateZnamky(Znamky instance);
    partial void DeleteZnamky(Znamky instance);
    partial void InsertPredmety(Predmety instance);
    partial void UpdatePredmety(Predmety instance);
    partial void DeletePredmety(Predmety instance);
    #endregion
		
		public KlasifikaceDataClassesDataContext() : 
				base(global::Projekt_BOOP.Properties.Settings.Default.KlasifikaceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KlasifikaceDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KlasifikaceDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KlasifikaceDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KlasifikaceDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fakulty> Fakulties
		{
			get
			{
				return this.GetTable<Fakulty>();
			}
		}
		
		public System.Data.Linq.Table<Studenti> Studentis
		{
			get
			{
				return this.GetTable<Studenti>();
			}
		}
		
		public System.Data.Linq.Table<StudentiList> StudentiLists
		{
			get
			{
				return this.GetTable<StudentiList>();
			}
		}
		
		public System.Data.Linq.Table<Hodnoceni> Hodnocenis
		{
			get
			{
				return this.GetTable<Hodnoceni>();
			}
		}
		
		public System.Data.Linq.Table<Znamky> Znamkies
		{
			get
			{
				return this.GetTable<Znamky>();
			}
		}
		
		public System.Data.Linq.Table<Predmety> Predmeties
		{
			get
			{
				return this.GetTable<Predmety>();
			}
		}
		
		public System.Data.Linq.Table<VypisPredmety> VypisPredmeties
		{
			get
			{
				return this.GetTable<VypisPredmety>();
			}
		}
		
		public System.Data.Linq.Table<VypisHodnoceni> VypisHodnocenis
		{
			get
			{
				return this.GetTable<VypisHodnoceni>();
			}
		}
		
		public System.Data.Linq.Table<VypisHodnoceniAlias> VypisHodnoceniAlias
		{
			get
			{
				return this.GetTable<VypisHodnoceniAlias>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fakulty")]
	public partial class Fakulty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _FakultaID;
		
		private string _FakultaNazev;
		
		private EntitySet<Studenti> _Studentis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFakultaIDChanging(short value);
    partial void OnFakultaIDChanged();
    partial void OnFakultaNazevChanging(string value);
    partial void OnFakultaNazevChanged();
    #endregion
		
		public Fakulty()
		{
			this._Studentis = new EntitySet<Studenti>(new Action<Studenti>(this.attach_Studentis), new Action<Studenti>(this.detach_Studentis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakultaID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short FakultaID
		{
			get
			{
				return this._FakultaID;
			}
			set
			{
				if ((this._FakultaID != value))
				{
					this.OnFakultaIDChanging(value);
					this.SendPropertyChanging();
					this._FakultaID = value;
					this.SendPropertyChanged("FakultaID");
					this.OnFakultaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakultaNazev", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FakultaNazev
		{
			get
			{
				return this._FakultaNazev;
			}
			set
			{
				if ((this._FakultaNazev != value))
				{
					this.OnFakultaNazevChanging(value);
					this.SendPropertyChanging();
					this._FakultaNazev = value;
					this.SendPropertyChanged("FakultaNazev");
					this.OnFakultaNazevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fakulty_Studenti", Storage="_Studentis", ThisKey="FakultaID", OtherKey="Fakulta")]
		public EntitySet<Studenti> Studentis
		{
			get
			{
				return this._Studentis;
			}
			set
			{
				this._Studentis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Studentis(Studenti entity)
		{
			this.SendPropertyChanging();
			entity.Fakulty = this;
		}
		
		private void detach_Studentis(Studenti entity)
		{
			this.SendPropertyChanging();
			entity.Fakulty = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Studenti")]
	public partial class Studenti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _StudentID;
		
		private string _Jmeno;
		
		private string _Prijmeni;
		
		private short _Fakulta;
		
		private short _Rocnik;
		
		private EntitySet<Hodnoceni> _Hodnocenis;
		
		private EntityRef<Fakulty> _Fakulty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnJmenoChanging(string value);
    partial void OnJmenoChanged();
    partial void OnPrijmeniChanging(string value);
    partial void OnPrijmeniChanged();
    partial void OnFakultaChanging(short value);
    partial void OnFakultaChanged();
    partial void OnRocnikChanging(short value);
    partial void OnRocnikChanged();
    #endregion
		
		public Studenti()
		{
			this._Hodnocenis = new EntitySet<Hodnoceni>(new Action<Hodnoceni>(this.attach_Hodnocenis), new Action<Hodnoceni>(this.detach_Hodnocenis));
			this._Fakulty = default(EntityRef<Fakulty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL")]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jmeno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Jmeno
		{
			get
			{
				return this._Jmeno;
			}
			set
			{
				if ((this._Jmeno != value))
				{
					this.OnJmenoChanging(value);
					this.SendPropertyChanging();
					this._Jmeno = value;
					this.SendPropertyChanged("Jmeno");
					this.OnJmenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijmeni", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prijmeni
		{
			get
			{
				return this._Prijmeni;
			}
			set
			{
				if ((this._Prijmeni != value))
				{
					this.OnPrijmeniChanging(value);
					this.SendPropertyChanging();
					this._Prijmeni = value;
					this.SendPropertyChanged("Prijmeni");
					this.OnPrijmeniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fakulta", DbType="SmallInt NOT NULL")]
		public short Fakulta
		{
			get
			{
				return this._Fakulta;
			}
			set
			{
				if ((this._Fakulta != value))
				{
					if (this._Fakulty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFakultaChanging(value);
					this.SendPropertyChanging();
					this._Fakulta = value;
					this.SendPropertyChanged("Fakulta");
					this.OnFakultaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rocnik", DbType="SmallInt NOT NULL")]
		public short Rocnik
		{
			get
			{
				return this._Rocnik;
			}
			set
			{
				if ((this._Rocnik != value))
				{
					this.OnRocnikChanging(value);
					this.SendPropertyChanging();
					this._Rocnik = value;
					this.SendPropertyChanged("Rocnik");
					this.OnRocnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Studenti_Hodnoceni", Storage="_Hodnocenis", ThisKey="Id", OtherKey="IdStud")]
		public EntitySet<Hodnoceni> Hodnocenis
		{
			get
			{
				return this._Hodnocenis;
			}
			set
			{
				this._Hodnocenis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fakulty_Studenti", Storage="_Fakulty", ThisKey="Fakulta", OtherKey="FakultaID", IsForeignKey=true)]
		public Fakulty Fakulty
		{
			get
			{
				return this._Fakulty.Entity;
			}
			set
			{
				Fakulty previousValue = this._Fakulty.Entity;
				if (((previousValue != value) 
							|| (this._Fakulty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fakulty.Entity = null;
						previousValue.Studentis.Remove(this);
					}
					this._Fakulty.Entity = value;
					if ((value != null))
					{
						value.Studentis.Add(this);
						this._Fakulta = value.FakultaID;
					}
					else
					{
						this._Fakulta = default(short);
					}
					this.SendPropertyChanged("Fakulty");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hodnocenis(Hodnoceni entity)
		{
			this.SendPropertyChanging();
			entity.Studenti = this;
		}
		
		private void detach_Hodnocenis(Hodnoceni entity)
		{
			this.SendPropertyChanging();
			entity.Studenti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentiList")]
	public partial class StudentiList
	{
		
		private int _ID;
		
		private string _Prijmeni;
		
		private string _Jmeno;
		
		private short _Rocnik;
		
		private string _Fakulta;
		
		public StudentiList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijmeni", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Prijmeni
		{
			get
			{
				return this._Prijmeni;
			}
			set
			{
				if ((this._Prijmeni != value))
				{
					this._Prijmeni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jmeno", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Jmeno
		{
			get
			{
				return this._Jmeno;
			}
			set
			{
				if ((this._Jmeno != value))
				{
					this._Jmeno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rocnik", DbType="SmallInt NOT NULL")]
		public short Rocnik
		{
			get
			{
				return this._Rocnik;
			}
			set
			{
				if ((this._Rocnik != value))
				{
					this._Rocnik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fakulta", DbType="NVarChar(50)")]
		public string Fakulta
		{
			get
			{
				return this._Fakulta;
			}
			set
			{
				if ((this._Fakulta != value))
				{
					this._Fakulta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hodnoceni")]
	public partial class Hodnoceni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdStud;
		
		private string _IdPredm;
		
		private float _Hodn;
		
		private EntityRef<Studenti> _Studenti;
		
		private EntityRef<Predmety> _Predmety;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdStudChanging(int value);
    partial void OnIdStudChanged();
    partial void OnIdPredmChanging(string value);
    partial void OnIdPredmChanged();
    partial void OnHodnChanging(float value);
    partial void OnHodnChanged();
    #endregion
		
		public Hodnoceni()
		{
			this._Studenti = default(EntityRef<Studenti>);
			this._Predmety = default(EntityRef<Predmety>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStud", DbType="Int NOT NULL")]
		public int IdStud
		{
			get
			{
				return this._IdStud;
			}
			set
			{
				if ((this._IdStud != value))
				{
					if (this._Studenti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdStudChanging(value);
					this.SendPropertyChanging();
					this._IdStud = value;
					this.SendPropertyChanged("IdStud");
					this.OnIdStudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPredm", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string IdPredm
		{
			get
			{
				return this._IdPredm;
			}
			set
			{
				if ((this._IdPredm != value))
				{
					if (this._Predmety.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPredmChanging(value);
					this.SendPropertyChanging();
					this._IdPredm = value;
					this.SendPropertyChanged("IdPredm");
					this.OnIdPredmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodn", DbType="Real NOT NULL")]
		public float Hodn
		{
			get
			{
				return this._Hodn;
			}
			set
			{
				if ((this._Hodn != value))
				{
					this.OnHodnChanging(value);
					this.SendPropertyChanging();
					this._Hodn = value;
					this.SendPropertyChanged("Hodn");
					this.OnHodnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Studenti_Hodnoceni", Storage="_Studenti", ThisKey="IdStud", OtherKey="Id", IsForeignKey=true)]
		public Studenti Studenti
		{
			get
			{
				return this._Studenti.Entity;
			}
			set
			{
				Studenti previousValue = this._Studenti.Entity;
				if (((previousValue != value) 
							|| (this._Studenti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Studenti.Entity = null;
						previousValue.Hodnocenis.Remove(this);
					}
					this._Studenti.Entity = value;
					if ((value != null))
					{
						value.Hodnocenis.Add(this);
						this._IdStud = value.Id;
					}
					else
					{
						this._IdStud = default(int);
					}
					this.SendPropertyChanged("Studenti");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Predmety_Hodnoceni", Storage="_Predmety", ThisKey="IdPredm", OtherKey="ZkratkaPredm", IsForeignKey=true)]
		public Predmety Predmety
		{
			get
			{
				return this._Predmety.Entity;
			}
			set
			{
				Predmety previousValue = this._Predmety.Entity;
				if (((previousValue != value) 
							|| (this._Predmety.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Predmety.Entity = null;
						previousValue.Hodnocenis.Remove(this);
					}
					this._Predmety.Entity = value;
					if ((value != null))
					{
						value.Hodnocenis.Add(this);
						this._IdPredm = value.ZkratkaPredm;
					}
					else
					{
						this._IdPredm = default(string);
					}
					this.SendPropertyChanged("Predmety");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Znamky")]
	public partial class Znamky : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private float _ZnamkaValue;
		
		private char _ZnamkaAlias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZnamkaValueChanging(float value);
    partial void OnZnamkaValueChanged();
    partial void OnZnamkaAliasChanging(char value);
    partial void OnZnamkaAliasChanged();
    #endregion
		
		public Znamky()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZnamkaValue", DbType="Real NOT NULL", IsPrimaryKey=true)]
		public float ZnamkaValue
		{
			get
			{
				return this._ZnamkaValue;
			}
			set
			{
				if ((this._ZnamkaValue != value))
				{
					this.OnZnamkaValueChanging(value);
					this.SendPropertyChanging();
					this._ZnamkaValue = value;
					this.SendPropertyChanged("ZnamkaValue");
					this.OnZnamkaValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZnamkaAlias", DbType="NChar(1) NOT NULL")]
		public char ZnamkaAlias
		{
			get
			{
				return this._ZnamkaAlias;
			}
			set
			{
				if ((this._ZnamkaAlias != value))
				{
					this.OnZnamkaAliasChanging(value);
					this.SendPropertyChanging();
					this._ZnamkaAlias = value;
					this.SendPropertyChanged("ZnamkaAlias");
					this.OnZnamkaAliasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Predmety")]
	public partial class Predmety : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ZkratkaPredm;
		
		private string _NazevPredm;
		
		private EntitySet<Hodnoceni> _Hodnocenis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZkratkaPredmChanging(string value);
    partial void OnZkratkaPredmChanged();
    partial void OnNazevPredmChanging(string value);
    partial void OnNazevPredmChanged();
    #endregion
		
		public Predmety()
		{
			this._Hodnocenis = new EntitySet<Hodnoceni>(new Action<Hodnoceni>(this.attach_Hodnocenis), new Action<Hodnoceni>(this.detach_Hodnocenis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZkratkaPredm", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ZkratkaPredm
		{
			get
			{
				return this._ZkratkaPredm;
			}
			set
			{
				if ((this._ZkratkaPredm != value))
				{
					this.OnZkratkaPredmChanging(value);
					this.SendPropertyChanging();
					this._ZkratkaPredm = value;
					this.SendPropertyChanged("ZkratkaPredm");
					this.OnZkratkaPredmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazevPredm", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazevPredm
		{
			get
			{
				return this._NazevPredm;
			}
			set
			{
				if ((this._NazevPredm != value))
				{
					this.OnNazevPredmChanging(value);
					this.SendPropertyChanging();
					this._NazevPredm = value;
					this.SendPropertyChanged("NazevPredm");
					this.OnNazevPredmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Predmety_Hodnoceni", Storage="_Hodnocenis", ThisKey="ZkratkaPredm", OtherKey="IdPredm")]
		public EntitySet<Hodnoceni> Hodnocenis
		{
			get
			{
				return this._Hodnocenis;
			}
			set
			{
				this._Hodnocenis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hodnocenis(Hodnoceni entity)
		{
			this.SendPropertyChanging();
			entity.Predmety = this;
		}
		
		private void detach_Hodnocenis(Hodnoceni entity)
		{
			this.SendPropertyChanging();
			entity.Predmety = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VypisPredmety")]
	public partial class VypisPredmety
	{
		
		private string _Zkratka;
		
		private string _Název;
		
		private System.Nullable<int> _Počet;
		
		private string _Průměr;
		
		public VypisPredmety()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zkratka", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string Zkratka
		{
			get
			{
				return this._Zkratka;
			}
			set
			{
				if ((this._Zkratka != value))
				{
					this._Zkratka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Název", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Název
		{
			get
			{
				return this._Název;
			}
			set
			{
				if ((this._Název != value))
				{
					this._Název = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Počet", DbType="Int")]
		public System.Nullable<int> Počet
		{
			get
			{
				return this._Počet;
			}
			set
			{
				if ((this._Počet != value))
				{
					this._Počet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Průměr", DbType="NVarChar(4000)")]
		public string Průměr
		{
			get
			{
				return this._Průměr;
			}
			set
			{
				if ((this._Průměr != value))
				{
					this._Průměr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VypisHodnoceni")]
	public partial class VypisHodnoceni
	{
		
		private string _ZkratkaJoin;
		
		private int _Id;
		
		private string _Jmeno;
		
		private string _Prijmeni;
		
		private string _ZkratkaPredm;
		
		private float _Hodnocení;
		
		private string _NazevPredm;
		
		public VypisHodnoceni()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZkratkaJoin", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ZkratkaJoin
		{
			get
			{
				return this._ZkratkaJoin;
			}
			set
			{
				if ((this._ZkratkaJoin != value))
				{
					this._ZkratkaJoin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jmeno", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Jmeno
		{
			get
			{
				return this._Jmeno;
			}
			set
			{
				if ((this._Jmeno != value))
				{
					this._Jmeno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijmeni", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prijmeni
		{
			get
			{
				return this._Prijmeni;
			}
			set
			{
				if ((this._Prijmeni != value))
				{
					this._Prijmeni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZkratkaPredm", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ZkratkaPredm
		{
			get
			{
				return this._ZkratkaPredm;
			}
			set
			{
				if ((this._ZkratkaPredm != value))
				{
					this._ZkratkaPredm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodnocení", DbType="Real NOT NULL")]
		public float Hodnocení
		{
			get
			{
				return this._Hodnocení;
			}
			set
			{
				if ((this._Hodnocení != value))
				{
					this._Hodnocení = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazevPredm", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazevPredm
		{
			get
			{
				return this._NazevPredm;
			}
			set
			{
				if ((this._NazevPredm != value))
				{
					this._NazevPredm = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VypisHodnoceniAlias")]
	public partial class VypisHodnoceniAlias
	{
		
		private int _Id;
		
		private string _Jmeno;
		
		private string _Prijmeni;
		
		private string _ZkratkaPredm;
		
		private char _Hodnocení;
		
		private string _NazevPredm;
		
		public VypisHodnoceniAlias()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jmeno", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Jmeno
		{
			get
			{
				return this._Jmeno;
			}
			set
			{
				if ((this._Jmeno != value))
				{
					this._Jmeno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijmeni", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Prijmeni
		{
			get
			{
				return this._Prijmeni;
			}
			set
			{
				if ((this._Prijmeni != value))
				{
					this._Prijmeni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZkratkaPredm", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string ZkratkaPredm
		{
			get
			{
				return this._ZkratkaPredm;
			}
			set
			{
				if ((this._ZkratkaPredm != value))
				{
					this._ZkratkaPredm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hodnocení", DbType="NChar(1) NOT NULL")]
		public char Hodnocení
		{
			get
			{
				return this._Hodnocení;
			}
			set
			{
				if ((this._Hodnocení != value))
				{
					this._Hodnocení = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazevPredm", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazevPredm
		{
			get
			{
				return this._NazevPredm;
			}
			set
			{
				if ((this._NazevPredm != value))
				{
					this._NazevPredm = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
